### ISSUE TITLE
Improve usibility of auto brace

### ISSUE THREAD

**Issue by frastlin** [derekriemer/nvda-notepadPlusPlus#3]
Currently I am having problems using the auto brace feature.
It may be me, but I am finding it more cumbersome than just typing my own braces.
If I have code like:
function fu(f){
	f()
}

fu(function(){
	for(i= 0;i<10i++){
		if(i==2){
			console.log("this is 2!")

I am given the following after:

		}
	}
}

Which is OK, but if I type my own brace the given brace doesn't go away. I also need to arrow down with my cursor at an unknown spot in relation to the brace. All of which lead to brace completion being slow and taking up more time than just doing braces myself.
I think that if there could be some way to jump to the next level quickly, it would improve the usefulness of this feature considerably.

An idea I had was by rerouting the NVDA+enter key to move to the next indentation level. another key that would work is NVDA+;.
This would do three things:
1. move to the brace after and place the cursor at the end of the line.
2. say the current indentation level or current line
3. enter in a new line at the current indentation once the NVDA key has been released.

This would allow one to jump several levels by pressing the ; key several times while holding down the NVDA key.

I will ask around to see what other screen reader users do in Visual Studio.
Thanks,

**Comment by tuukkao** [comment]
I think this issue could be better served with a Notepad++ plugin that
would do the focus change.

2016-11-22 21:56 GMT+02:00 Brandon <notifications@github.com>:

**Comment by derekriemer** [comment]
Agree.
