### ISSUE TITLE
Autocomplete suggestions no longer functional on NVDA 2022.4

### ISSUE THREAD

**Issue by TheQuinbox** [derekriemer/nvda-notepadPlusPlus#35]
Whenever the autocomplete suggestions dialog pops up, NVDA just reads blank. Arrowing, backspacing, typing, etc., also results in this. While this is happening, the log is being spammed with:
WARNING - stdout (05:32:02.269) - winInputHook (20332):
None
WARNING - stdout (05:32:02.373) - winInputHook (20332):
None
WARNING - stdout (05:32:02.413) - winInputHook (20332):
None
WARNING - stdout (05:32:02.613) - winInputHook (20332):
None
WARNING - stdout (05:32:02.778) - winInputHook (20332):
None
WARNING - stdout (05:32:02.869) - winInputHook (20332):
None
WARNING - stdout (05:32:02.886) - winInputHook (20332):
None
WARNING - stdout (05:32:03.068) - winInputHook (20332):
None
WARNING - stdout (05:32:03.097) - winInputHook (20332):
None
WARNING - stdout (05:32:03.518) - winInputHook (20332):
None
WARNING - stdout (05:32:03.544) - winInputHook (20332):
None
WARNING - stdout (05:32:03.697) - winInputHook (20332):
None
WARNING - stdout (05:32:03.800) - winInputHook (20332):
(20, False)
WARNING - stdout (05:32:03.984) - winInputHook (20332):
None
WARNING - stdout (05:32:04.158) - winInputHook (20332):
None
WARNING - stdout (05:32:04.417) - winInputHook (20332):
None
WARNING - stdout (05:32:04.587) - winInputHook (20332):
None
NVDA 2022.4.

**Comment by munawarb** [comment]
I rolled back a notepad++ upgrade to avoid this issue. But I don't remember what version I'm on. I'll find out and let you know.On Jan 8, 2023, at 7:32 AM, Quin ***@***.***> wrote:﻿
Whenever the autocomplete suggestions dialog pops up, NVDA just reads blank. Arrowing, backspacing, typing, etc., also results in this. While this is happening, the log is being spammed with:
WARNING - stdout (05:32:02.269) - winInputHook (20332):
None
WARNING - stdout (05:32:02.373) - winInputHook (20332):
None
WARNING - stdout (05:32:02.413) - winInputHook (20332):
None
WARNING - stdout (05:32:02.613) - winInputHook (20332):
None
WARNING - stdout (05:32:02.778) - winInputHook (20332):
None
WARNING - stdout (05:32:02.869) - winInputHook (20332):
None
WARNING - stdout (05:32:02.886) - winInputHook (20332):
None
WARNING - stdout (05:32:03.068) - winInputHook (20332):
None
WARNING - stdout (05:32:03.097) - winInputHook (20332):
None
WARNING - stdout (05:32:03.518) - winInputHook (20332):
None
WARNING - stdout (05:32:03.544) - winInputHook (20332):
None
WARNING - stdout (05:32:03.697) - winInputHook (20332):
None
WARNING - stdout (05:32:03.800) - winInputHook (20332):
(20, False)
WARNING - stdout (05:32:03.984) - winInputHook (20332):
None
WARNING - stdout (05:32:04.158) - winInputHook (20332):
None
WARNING - stdout (05:32:04.417) - winInputHook (20332):
None
WARNING - stdout (05:32:04.587) - winInputHook (20332):
None
NVDA 2022.4.

**Comment by TheQuinbox** [comment]
Hmm, interesting. Just tried updating to the latest version of both NVDA and NPP on another computer, and its not happening. It is an NVDA alpha though, so maybe they broke it for like 5 microseconds, and then fixed. Will have to do more testing.

**Comment by TheQuinbox** [comment]
Yup, just updated to the latest NVDA alpha, and its fixed, on the machine I originally reported this from. Going to close this, but @munawarb or anyone else who continues to run into this after 2022.4, feel free to reopen/comment.
